ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION}

# Zależności systemowe
RUN apt update && apt install -y \
    curl gnupg2 lsb-release \
    git python3-pip \
    locales sudo \
    build-essential \
    x11-apps \
    mesa-utils \
    pciutils \
    && locale-gen en_US en_US.UTF-8 \
    && rm -rf /var/lib/apt/lists/*

# Instalacja colcon-common-extensions za pomocą pip3 z flagą --break-system-packages
RUN pip3 install --break-system-packages -U colcon-common-extensions

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
# Usunięto LIBGL_ALWAYS_SOFTWARE=1 aby umożliwić akcelerację sprzętową
# ENV LIBGL_ALWAYS_SOFTWARE=1  
ENV GZ_SIM_SYSTEM_PLUGIN_PATH=/opt/ros/jazzy/lib/

# Zmienne środowiskowe dla akceleracji Nvidia
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

# Dodanie zmiennej XDG_RUNTIME_DIR oraz utworzenie katalogu z odpowiednimi uprawnieniami
ENV XDG_RUNTIME_DIR=/tmp/runtime-root
RUN mkdir -p /tmp/runtime-root && chmod 0700 /tmp/runtime-root

# ROS2 Jazzy oraz pakiety ros-jazzy: desktop, ros-gz-sim, ros-gz-bridge, control-msgs, backward-ros, controller-interface, control-toolbox, xacro
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2.list && \
    apt update && \
    apt install -y \
    ros-jazzy-desktop \
    ros-jazzy-ros-gz-sim \
    ros-jazzy-ros-gz-bridge \
    ros-jazzy-control-msgs \
    ros-jazzy-backward-ros \
    ros-jazzy-controller-interface \
    ros-jazzy-control-toolbox \
    ros-jazzy-xacro \
    ros-jazzy-ros2-control \
    ros-jazzy-ros2-controllers \
    ros-jazzy-controller-manager \
    ros-jazzy-joint-state-publisher \
    ros-jazzy-robot-state-publisher \
    ros-jazzy-hardware-interface \
    ros-jazzy-gz-ros2-control

# Gazebo Harmonic
RUN curl -sSL https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list && \
    apt update && \
    apt install -y gz-harmonic

# Dodanie pakietów MoveIt
RUN apt install -y ros-jazzy-moveit-* --no-install-recommends && rm -rf /var/lib/apt/lists/*

# Dodanie narzędzi diagnostycznych dla GPU
RUN apt install -y \
    mesa-utils \
    glmark2 \
    vulkan-tools \
    pciutils \
    hwinfo \
    radeontop \
    && if command -v apt-cache >/dev/null && apt-cache search nvidia-utils | grep -q nvidia-utils; then \
        apt install -y $(apt-cache search nvidia-utils | grep -E 'nvidia-utils-[0-9]+$' | sort -V | tail -n1 | awk '{print $1}') || true; \
    fi \
    && rm -rf /var/lib/apt/lists/*

# Source ROS2
RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc

# Pobranie/aktualizacja kodu i build
WORKDIR /root
RUN if [ -d "Hexapod" ]; then \
        echo "Repozytorium istnieje, aktualizowanie..." && \
        cd Hexapod && \
        git pull; \
    else \
        echo "Klonowanie repozytorium..." && \
        git clone https://github.com/Siedmiu/Hexapod.git; \
    fi && \
    cd Hexapod/sim_and_real/ros2_ws_hex && \
    bash -c "source /opt/ros/jazzy/setup.bash && colcon build"

# Source workspace
RUN echo "source /root/Hexapod/sim_and_real/ros2_ws_hex/install/setup.bash" >> /root/.bashrc

# Domyślnie uruchamiana symulacja
CMD ["/bin/bash", "-c", "source /opt/ros/jazzy/setup.bash && source /root/Hexapod/sim_and_real/ros2_ws_hex/install/setup.bash && ros2 launch hex_gz gazebo.launch.py"]

