# Konfiguracja dla ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    hexapod_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Konfiguracja kontrolera ramienia hexapoda
hexapod_arm_controller:
  ros__parameters:
    joints:
      - up_section_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

    state_publish_rate: 50
    action_monitor_rate: 20
    goal_tolerance: 0.01
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 1.0
      up_section_joint:
        trajectory: 0.05
        goal: 0.01
      mid_section_joint:
        trajectory: 0.05
        goal: 0.01
      down_section_joint:
        trajectory: 0.05
        goal: 0.01
